### ISSUE TITLE
Invalid records on creation and parsing

### ISSUE THREAD

**Issue by martinhartmann** [Badcow/DNS#33]
I can create invalid records with this library and am not able to parse zonefiles with invalid records (e.g. skip invalid records).

Test script:
```
<?php


declare(strict_types = 1);


use Badcow\DNS\Parser\Parser;
use Badcow\DNS\Rdata\MX;
use Badcow\DNS\ResourceRecord;
use Badcow\DNS\Zone;
use Badcow\DNS\ZoneBuilder;


require __DIR__."/../vendor/autoload.php";

// create zone
$z  = new Zone( "example.org" );
$mx = new MX();
$mx->setExchange( "foo" );
$r = new ResourceRecord( "foo", $mx );
$z->addResourceRecord( $r );
$zone = ZoneBuilder::build( $z );
echo "$zone\n\n\n";

// parse created zone
$parsedZone = Parser::parse( "example.org", $zone );
$pz         = ZoneBuilder::build( $parsedZone );
echo "$pz\n\n\n";
```

Output:
```
// create zone
$ORIGIN example.org
foo MX foo // invalid



// parse created zone
Fatal error: Uncaught ArgumentCountError: Too few arguments to function Badcow\DNS\Rdata\Factory::Mx(), 1 passed and exactly 2 expected in vendor/badcow/dns/lib/Rdata/Factory.php:125
Stack trace:
#0 [internal function]: Badcow\DNS\Rdata\Factory::Mx('foo')
#1 vendor/badcow/dns/lib/Parser/RdataHandlers.php(147): call_user_func_array(Array, Array)
#2 vendor/badcow/dns/lib/Parser/Parser.php(224): Badcow\DNS\Parser\RdataHandlers::catchAll('MX', Object(ArrayIterator))
#3 vendor/badcow/dns/lib/Parser/Parser.php(106): Badcow\DNS\Parser\Parser->extractRdata(Object(ArrayIterator))
#4 vendor/badcow/dns/lib/Parser/Parser.php(80): Badcow\DNS\Parser\Parser->processLine('foo MX foo')
#5 vendor/badcow/dns/lib/Parser/Parser.php(63): Badcow\DNS\Parser\Parser->makeZone('example.org', '$ORIGIN example...')
#6 bin/test.php(24): Badcow\DNS\Parser\Parser::parse('example.or in vendor/badcow/dns/lib/Rdata/Factory.php on line 125
```

This should be handled by the library of not beeing able to create invalid data.

**Comment by samuelwilliams** [comment]
@martinhartmann thank you for the issue. I have added an exception to the `Rdata\MX` object which will now fail before being generated.
